### PR TITLE
Composition API Component Fix

### LINKED ISSUE #5: Update to also use Vue 3 app.provide + app.inject and update README
The install function should do:

```
app.provide('emitExtendable');
```

So this can be called from `setup()`:

```
import {inject} from 'vue';

// ...

setup() {
  const emitExtendable = inject('emitExtendable');

  // ...
}
```

### PR DESCRIPTION
**Pull request by jameseaster**
#### _Resolves #5_

Include emit function as optional parameter for Composition API components

---

### What kind of change does this PR introduce?

- Feature extension.

<br/>

### What is the current behavior?

- Composition API components error out when using emitExtendable.

<br/>

### What is the new behavior?

- The function emitExtendable accepts `emit` as an optional parameter.
- README has been updated with a Vue 3 Composition API example.

<br/>

### Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

<br/>

### How has this been tested?

- Locally.

<br/>

### Screenshots: n/a

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -7,7 +7,13 @@ export default function install(app) {
   app.config.globalProperties.$emitExtendable = emitExtendable;
 }
 
-export function createEmitExtendable() {
+export function createEmitExtendable({emit}) {
+  if(!emit && !getCurrentInstance()) {
+    throw new TypeError('Emit function is not present.');
```
Comment (dlongley) [inline lib/index.js]:
```suggestion
    throw new TypeError(
      '"emit" is required when there is no current component instance.');
```

**Review by dlongley — APPROVED** [review]

File: lib/index.js [hunk 2]
```diff
@@ -7,7 +7,14 @@ export default function install(app) {
...
 
-export function createEmitExtendable() {
+export function createEmitExtendable({emit}) {
+  if(!emit && !getCurrentInstance()) {
+    throw new TypeError(
+      '"emit" is required when there is no current component instance.');
+  }
+  if(emit) {
+    return emitExtendable.bind({emit});
+  }
```
Comment (dlongley) [inline lib/index.js]:
```suggestion
  if(emit) {
    return emitExtendable.bind({emit});
  }
  if(!getCurrentInstance()) {
    throw new TypeError(
      '"emit" is required when there is no current component instance.');
  }
```
